REVOKE ALL ON SCHEMA __SCHEMA__ FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA __SCHEMA__ FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA __SCHEMA__ FROM PUBLIC;

REVOKE ALL ON SCHEMA __SCHEMA__ FROM __RUNTIME_ROLE__;
REVOKE ALL ON ALL TABLES IN SCHEMA __SCHEMA__ FROM __RUNTIME_ROLE__;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA __SCHEMA__ FROM __RUNTIME_ROLE__;

GRANT USAGE ON SCHEMA __SCHEMA__ TO __RUNTIME_ROLE__;
GRANT SELECT ON __SCHEMA__.policy_runtime_revisions TO __RUNTIME_ROLE__;
GRANT SELECT, INSERT ON __SCHEMA__.approval_decisions TO __RUNTIME_ROLE__;
GRANT SELECT, INSERT ON __SCHEMA__.approval_status_revisions TO __RUNTIME_ROLE__;
GRANT SELECT, INSERT ON __SCHEMA__.policy_rate_consumptions TO __RUNTIME_ROLE__;
GRANT SELECT, INSERT ON __SCHEMA__.approval_idempotency_receipts TO __RUNTIME_ROLE__;
GRANT SELECT, INSERT ON __SCHEMA__.approval_outbox TO __RUNTIME_ROLE__;
GRANT SELECT, INSERT ON __SCHEMA__.approval_idempotency_quarantine TO __RUNTIME_ROLE__;

ALTER DEFAULT PRIVILEGES IN SCHEMA __SCHEMA__ REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA __SCHEMA__ REVOKE ALL ON FUNCTIONS FROM PUBLIC;
