REVOKE ALL ON SCHEMA __SCHEMA__ FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA __SCHEMA__ FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA __SCHEMA__ FROM PUBLIC;

REVOKE ALL ON SCHEMA __SCHEMA__ FROM __RUNTIME_ROLE__;
REVOKE ALL ON ALL TABLES IN SCHEMA __SCHEMA__ FROM __RUNTIME_ROLE__;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA __SCHEMA__ FROM __RUNTIME_ROLE__;

GRANT USAGE ON SCHEMA __SCHEMA__ TO __RUNTIME_ROLE__;
GRANT SELECT, INSERT ON __SCHEMA__.audit_events TO __RUNTIME_ROLE__;
GRANT SELECT, INSERT ON __SCHEMA__.audit_quarantine TO __RUNTIME_ROLE__;
GRANT SELECT ON __SCHEMA__.audit_relay_trust_states TO __RUNTIME_ROLE__;
GRANT EXECUTE ON FUNCTION __SCHEMA__.jsonb_has_exact_keys(jsonb, text[]) TO __RUNTIME_ROLE__;

ALTER DEFAULT PRIVILEGES IN SCHEMA __SCHEMA__ REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA __SCHEMA__ REVOKE ALL ON FUNCTIONS FROM PUBLIC;
