<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><AssemblyName>Dps.OperationCompiler</AssemblyName><RootNamespace>Dps.OperationCompiler</RootNamespace><PackageId>Dps.OperationCompiler</PackageId><Version>0.3.0</Version></PropertyGroup><ItemGroup><ProjectReference Include="../../contracts/provided/Dps.OperationCompiler.Contracts/Dps.OperationCompiler.Contracts.csproj" /><ProjectReference Include="../../../policy-approval/contracts/provided/Dps.PolicyApproval.Contracts/Dps.PolicyApproval.Contracts.csproj" /><InternalsVisibleTo Include="Dps.OperationCompiler.Tests" /></ItemGroup></Project>
