<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><AssemblyName>Dps.ExecutorGateway</AssemblyName><RootNamespace>Dps.ExecutorGateway</RootNamespace><PackageId>Dps.ExecutorGateway</PackageId><Version>0.1.2</Version></PropertyGroup><ItemGroup><Compile Remove="EcdsaNativeStopProofVerifier.cs" /><ProjectReference Include="../../contracts/provided/Dps.ExecutorGateway.Contracts/Dps.ExecutorGateway.Contracts.csproj" /><ProjectReference Include="../../../command-orchestrator/contracts/provided/Dps.CommandOrchestrator.Contracts/Dps.CommandOrchestrator.Contracts.csproj" /><ProjectReference Include="../../../policy-approval/contracts/provided/Dps.PolicyApproval.Contracts/Dps.PolicyApproval.Contracts.csproj" /></ItemGroup></Project>
